# Generated by Django 5.2.4 on 2025-08-01 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CaseQuery',
        ),
    ]
