# Generated by Django 5.2.4 on 2025-08-01 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0002_delete_casequery'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_type', models.CharField(max_length=50)),
                ('case_number', models.IntegerField()),
                ('filing_year', models.IntegerField()),
                ('raw_json', models.TextField()),
                ('queried_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
