from django import forms

CASE_TYPES = [
    (' ', "Case Type"),
    ('ADMIN.REPORT', 'ADMIN.REPORT'),
    ('ARB.A.', 'ARB.A.'),
    ('ARB. A. (COMM.)', 'ARB. A. (COMM.)'),
    ('ARB.P.', 'ARB.P.'),
    ('BAIL APPLN.', 'BAIL APPLN.'),
    ('CA', 'CA'),
    ('CA (COMM.IPD-CR)', 'CA (COMM.IPD-CR)'),
    ('C.A.(COMM.IPD-GI)', 'C.A.(COMM.IPD-GI)'),
    ('C.A.(COMM.IPD-PAT)', 'C.A.(COMM.IPD-PAT)'),
    ('C.A.(COMM.IPD-PV)', 'C.A.(COMM.IPD-PV)'),
    ('C.A.(COMM.IPD-TM)', 'C.A.(COMM.IPD-TM)'),
    ('CAVEAT(CO.)', 'CAVEAT(CO.)'),
    ('CC(ARB.)', 'CC(ARB.)'),
    ('CCP(CO.)', 'CCP(CO.)'),
    ('CCP(REF)', 'CCP(REF)'),
    ('CEAC', 'CEAC'),
    ('CEAR', 'CEAR'),
    ('CHAT.A.C.', 'CHAT.A.C.'),
    ('CHAT.A.REF', 'CHAT.A.REF'),
    ('CMI', 'CMI'),
    ('CM(M)', 'CM(M)'),
    ('CM(M)-IPD', 'CM(M)-IPD'),
    ('C.O.', 'C.O.'),
    ('CO.APP.', 'CO.APP.'),
    ('CO.APPL.(C)', 'CO.APPL.(C)'),
    ('CO.APPL.(M)', 'CO.APPL.(M)'),
    ('CO.A(SB)', 'CO.A(SB)'),
    ('C.O.(COMM.IPD-CR)', 'C.O.(COMM.IPD-CR)'),
    ('C.O.(COMM.IPD-GI)', 'C.O.(COMM.IPD-GI)'),
    ('C.O.(COMM.IPD-PAT)', 'C.O.(COMM.IPD-PAT)'),
    ('C.O.(COMM.IPD-TM)', 'C.O.(COMM.IPD-TM)'),
    ('CO.EX.', 'CO.EX.'),
    ('CONT.APP.(C)', 'CONT.APP.(C)'),
    ('CONT.CAS(C)', 'CONT.CAS(C)'),
    ('CONT.CAS.(CRL)', 'CONT.CAS.(CRL)'),
    ('CO.PET.', 'CO.PET.'),
    ('C.REF.(O)', 'C.REF.(O)'),
    ('CRL.A.', 'CRL.A.'),
    ('CRL.L.P.', 'CRL.L.P.'),
    ('CRL.M.C.', 'CRL.M.C.'),
    ('CRL.M.(CO.)', 'CRL.M.(CO.)'),
    ('CRL.M.I.', 'CRL.M.I.'),
    ('CRL.O.', 'CRL.O.'),
    ('CRL.O.(CO.)', 'CRL.O.(CO.)'),
    ('CRL.REF.', 'CRL.REF.'),
    ('CRL.REV.P.', 'CRL.REV.P.'),
    ('CRL.REV.P.(MAT.)', 'CRL.REV.P.(MAT.)'),
    ('CRL.REV.P.(NDPS)', 'CRL.REV.P.(NDPS)'),
    ('CRL.REV.P.(NI)', 'CRL.REV.P.(NI)'),
    ('C.R.P.', 'C.R.P.'),
    ('CRP-IPD', 'CRP-IPD'),
    ('C.RULE', 'C.RULE'),
    ('CS(COMM)', 'CS(COMM)'),
    ('CS(OS)', 'CS(OS)'),
    ('CS(OS) GP', 'CS(OS) GP'),
    ('CUSAA', 'CUSAA'),
    ('CUS.A.C.', 'CUS.A.C.'),
    ('CUS.A.R.', 'CUS.A.R.'),
    ('CUSTOM A.', 'CUSTOM A.'),
    ('DEATH SENTENCE REF.', 'DEATH SENTENCE REF.'),
    ('DEMO', 'DEMO'),
    ('EDC', 'EDC'),
    ('EDR', 'EDR'),
    ('EFA(COMM)', 'EFA(COMM)'),
    ('EFA(OS)', 'EFA(OS)'),
    ('EFA(OS) (COMM)', 'EFA(OS) (COMM)'),
    ('EFA(OS)(IPD)', 'EFA(OS)(IPD)'),
    ('EL.PET.', 'EL.PET.'),
    ('ETR', 'ETR'),
    ('EX.F.A.', 'EX.F.A.'),
    ('EX.P.', 'EX.P.'),
    ('EX.S.A.', 'EX.S.A.'),
    ('FAO', 'FAO'),
    ('FAO (COMM)', 'FAO (COMM)'),
    ('FAO-IPD', 'FAO-IPD'),
    ('FAO(OS)', 'FAO(OS)'),
    ('FAO(OS) (COMM)', 'FAO(OS) (COMM)'),
    ('FAO(OS)(IPD)', 'FAO(OS)(IPD)'),
    ('GCAC', 'GCAC'),
    ('GCAR', 'GCAR'),
    ('GTA', 'GTA'),
    ('GTC', 'GTC'),
    ('GTR', 'GTR'),
    ('I.A.', 'I.A.'),
    ('I.P.A.', 'I.P.A.'),
    ('ITA', 'ITA'),
    ('ITC', 'ITC'),
    ('ITR', 'ITR'),
    ('ITSA', 'ITSA'),
    ('LA.APP.', 'LA.APP.'),
    ('LPA', 'LPA'),
    ('MAC.APP.', 'MAC.APP.'),
    ('MAT.', 'MAT.'),
    ('MAT.APP.', 'MAT.APP.'),
    ('MAT.APP.(F.C.)', 'MAT.APP.(F.C.)'),
    ('MAT.CASE', 'MAT.CASE'),
    ('MAT.REF.', 'MAT.REF.'),
    ('MISC. APPEAL(PMLA)', 'MISC. APPEAL(PMLA)'),
    ('OA', 'OA'),
    ('OCJA', 'OCJA'),
    ('O.M.P', 'O.M.P'),
    ('O.M.P. (COMM)', 'O.M.P. (COMM)'),
    ('OMP (CONT.)', 'OMP (CONT.)'),
    ('O.M.P. (E)', 'O.M.P. (E)'),
    ('O.M.P. (E) (COMM.)', 'O.M.P. (E) (COMM.)'),
    ('O.M.P.(EFA)(COMM.)', 'O.M.P.(EFA)(COMM.)'),
    ('OMP (ENF.) (COMM.)', 'OMP (ENF.) (COMM.)'),
    ('O.M.P.(I)', 'O.M.P.(I)'),
    ('O.M.P.(I) (COMM.)', 'O.M.P.(I) (COMM.)'),
    ('O.M.P. (J) (COMM.)', 'O.M.P. (J) (COMM.)'),
    ('O.M.P. (MISC.)', 'O.M.P. (MISC.)'),
    ('O.M.P.(MISC.)(COMM.)', 'O.M.P.(MISC.)(COMM.)'),
    ('O.M.P.(T)', 'O.M.P.(T)'),
    ('O.M.P. (T) (COMM.)', 'O.M.P. (T) (COMM.)'),
    ('O.REF.', 'O.REF.'),
    ('RC.REV.', 'RC.REV.'),
    ('RC.S.A.', 'RC.S.A.'),
    ('RFA', 'RFA'),
    ('RFA(COMM)', 'RFA(COMM)'),
    ('RFA-IPD', 'RFA-IPD'),
    ('RFA(OS)', 'RFA(OS)'),
    ('RFA(OS)(COMM)', 'RFA(OS)(COMM)'),
    ('RF(OS)(IPD)', 'RF(OS)(IPD)'),
    ('RSA', 'RSA'),
    ('SCA', 'SCA'),
    ('SDR', 'SDR'),
    ('SERTA', 'SERTA'),
    ('ST.APPL.', 'ST.APPL.'),
    ('STC', 'STC'),
    ('ST.REF.', 'ST.REF.'),
    ('SUR.T.REF.', 'SUR.T.REF.'),
    ('TEST.CAS.', 'TEST.CAS.'),
    ('TR.P.(C)', 'TR.P.(C)'),
    ('TR.P.(C.)', 'TR.P.(C.)'),
    ('TR.P.(CRL.)', 'TR.P.(CRL.)'),
    ('VAT APPEAL', 'VAT APPEAL'),
    ('W.P.(C)', 'W.P.(C)'),
    ('W.P.(C)-IPD', 'W.P.(C)-IPD'),
    ('WP(C)(IPD)', 'WP(C)(IPD)'),
    ('W.P.(CRL)', 'W.P.(CRL)'),
    ('WTA', 'WTA'),
    ('WTC', 'WTC'),
    ('WTR', 'WTR'),
]


class CaseSearchForm(forms.Form):
    case_type = forms.ChoiceField(
        choices=CASE_TYPES,
        widget=forms.Select(attrs={
            'style': 'width:220px; padding:6px; font-size:14px;'
        })
    )
    case_number = forms.CharField(
        widget=forms.TextInput(attrs={
            'placeholder': 'Enter Case Number',
            'style': 'width:220px; padding:6px; font-size:14px;'
        })
    )
    filing_year = forms.CharField(
        widget=forms.TextInput(attrs={
            'placeholder': 'Enter Filing Year',
            'style': 'width:220px; padding:6px; font-size:14px;'
        })
    )
